[versions]
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
versionCode = "1"
appVersion = "1.0.0"

# kotlin
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.9.0"
ksp = "2.1.0-1.0.29"

# android
agp = "8.13.1"
activityCompose = "1.11.0"
androidxComposeFoundation = "1.9.4"
androidxLifecycle = "2.9.4"
androidxNavigation = "2.9.6"
androidxCoreSplashscreen = "1.2.0"
androidxDataStore = "1.1.7"
androidxEspresso = "3.7.0"
androidxTestCore = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.7.0"
androidxUiAutomator = "2.3.0"
coreKtx = "1.17.0"
composeBom = "2025.11.00"
room = "2.8.3"
robolectric = "4.16"

# google
protobuf = "4.33.1"
protobufPlugin = "0.9.5"

# third-party
coil = "2.7.0"
moduleGraph = "2.7.1"
koin = "4.1.1"
ktlint = "14.0.1"
timber = "5.0.1"

# test
androidJunit5Plugin = "1.14.0.0"
androidJunit5Core = "1.9.0"
mockk = "1.14.6"
truth = "1.4.4"
junit4 = "4.13.2"
junit5Jupiter = "6.0.1"
kotestRunnerJunit5 = "6.0.4"
assertj = "3.27.6"

[libraries]
# kotlin
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# androidx
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxComposeFoundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "androidxDataStore" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidxTestCore" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# google
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# third-party
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-test-junit5 = { group = "io.insert-koin", name = "test-junit5" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
koin-androidx-compose-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation" }
koin-android-test = { group = "io.insert-koin", name = "koin-android-test" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# test
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit5 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5Jupiter" }
junit5-params= {group= "org.junit.jupiter", name="junit-jupiter-params", version.ref="junit5Jupiter"}
junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidJunit5Core" }
junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidJunit5Core" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5Jupiter" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotestRunnerJunit5" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }


[bundles]
compose = [
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material-iconsExtended",
    "androidx-material3",
]
unit-test = ["kotlinx-test", "kotlinx-coroutines-test", "junit5", "junit5-params", "kotest-runner-junit5", "mockk"]
androidx-android-test = ["androidx-test-ext", "androidx-test-runner", "androidx-test-rules"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5Plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
module-graph = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraph" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Plugins defined by murjune
murjune-jvm-library = { id = "com.murjune.practice.jvm.library" }
murjune-kotlinx-serialization = { id = "com.murjune.practice.kotlinx_serialization" }
# Plugins defined by Android
murjune-android-application = { id = "com.murjune.practice.application" }
murjune-android-compose = { id = "com.murjune.practice.compose" }
murjune-android-feature = { id = "com.murjune.practice.feature" }
murjune-android-library = { id = "com.murjune.practice.library" }
murjune-unit-test = { id = "com.murjune.practice.unit.test" }
